#!/bin/bash

sudo apt-get install -y software-properties-common

sudo add-apt-repository ppa:webupd8team/java -y
sudo apt-get -y update
sudo apt-get install -y oracle-java8-installer
sudo apt-get install -y oracle-java8-set-default

sudo apt install mysql-server
