#!/bin/bash

sudo apt-get install -y software-properties-common

sudo add-apt-repository ppa:webupd8team/java -y
sudo apt-get -y update
sudo apt-get install -y oracle-java8-installer
sudo apt-get install -y oracle-java8-set-default

sudo apt-get install -y git
sudo apt-get install -y maven
sudo apt-get install -y ant

sudo apt install -y mysql-server

wget http://mirror.fibergrid.in/apache/tomcat/tomcat-8/v8.0.33/bin/apache-tomcat-8.0.33.zip
sudo mkdir tomcat
unzip apache-tomcat-8.0.33.zip -d tomcat
sudo mkdir -p /opt/tomcat
mv tomcat/apache-tomcat-8.0.33/* /opt/tomcat
